server:
  port: 8083

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/accounts_db?createDatabaseIfNotExist=true
    username: ${MYSQL_USER:fidele}
    password: ${MYSQL_PASSWORD:Dev_**Hacker**@2024#}

  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
